{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapError"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"F"},{"kind":"text","text":">("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"f"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"F"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal","preciseIdentifier":"s:13ReactiveSwift6SignalC","text":"Signal"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Value"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"F"},{"kind":"text","text":">."},{"kind":"typeIdentifier","identifier":"doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal\/Event","preciseIdentifier":"s:13ReactiveSwift6SignalC5EventO","text":"Event"},{"kind":"text","text":" "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"F"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An event with function applied to an error object in case"},{"type":"text","text":" "},{"type":"codeVoice","code":"self"},{"type":"text","text":" is a "},{"type":"codeVoice","code":".Failed"},{"type":"text","text":" type of event."}]}]},{"kind":"parameters","parameters":[{"name":"f","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that accepts an error object and returns"},{"type":"text","text":" "},{"type":"text","text":"a new error object"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The closure is called only on failed type event."}]}]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/reactiveswift\/signal\/event\/maperror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal\/Event\/mapError(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Lift the given closure over the event’s error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapError"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"F"},{"kind":"text","text":">(("},{"kind":"typeIdentifier","text":"Error"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"F"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:13ReactiveSwift6SignalC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Value"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"F"},{"kind":"text","text":">."},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:13ReactiveSwift6SignalC5EventO"}],"title":"mapError(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:13ReactiveSwift6SignalC5EventO8mapErroryAEyxqd___Gqd__q_XEs0F0Rd__lF","modules":[{"name":"ReactiveSwift"}]},"hierarchy":{"paths":[["doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift","doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal","doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal\/Event"]]},"references":{"doc://ReactiveSwift/documentation/ReactiveSwift/Signal/Event":{"conformance":{"constraints":[{"type":"codeVoice","code":"Error"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Error"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol","title":"Signal.Event","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"abstract":[{"type":"text","text":"Represents a signal event."}],"identifier":"doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal\/Event","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Event"}],"url":"\/documentation\/reactiveswift\/signal\/event"},"doc://ReactiveSwift/documentation/ReactiveSwift/Signal":{"role":"symbol","title":"Signal","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signal"}],"abstract":[{"type":"text","text":"A push-driven stream that sends Events over time, parameterized by the type"},{"type":"text","text":" "},{"type":"text","text":"of values being sent ("},{"type":"codeVoice","code":"Value"},{"type":"text","text":") and the type of failure that can occur"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":"Error"},{"type":"text","text":"). If no failures should be possible, Never can be specified for"},{"type":"text","text":" "},{"type":"codeVoice","code":"Error"},{"type":"text","text":"."}],"identifier":"doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Signal"}],"url":"\/documentation\/reactiveswift\/signal"},"doc://ReactiveSwift/documentation/ReactiveSwift/Signal/Event/mapError(_:)":{"role":"symbol","title":"mapError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapError"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"F"},{"kind":"text","text":">(("},{"kind":"typeIdentifier","text":"Error"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"F"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Signal","preciseIdentifier":"s:13ReactiveSwift6SignalC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Value"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"F"},{"kind":"text","text":">."},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:13ReactiveSwift6SignalC5EventO"}],"abstract":[{"type":"text","text":"Lift the given closure over the event’s error."}],"identifier":"doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift\/Signal\/Event\/mapError(_:)","kind":"symbol","type":"topic","url":"\/documentation\/reactiveswift\/signal\/event\/maperror(_:)"},"doc://ReactiveSwift/documentation/ReactiveSwift":{"role":"collection","title":"ReactiveSwift","abstract":[],"identifier":"doc:\/\/ReactiveSwift\/documentation\/ReactiveSwift","kind":"symbol","type":"topic","url":"\/documentation\/reactiveswift"}}}