{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/reactiveswiftrex\/fireandforget\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ReactiveSwiftRex\/documentation\/ReactiveSwiftRex\/FireAndForget\/Error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of error that can occur on "},{"type":"codeVoice","code":"self"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"FireAndForget.Error","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"s:16ReactiveSwiftRex13FireAndForgetV5Errora","modules":[{"name":"ReactiveSwiftRex"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}]},"hierarchy":{"paths":[["doc:\/\/ReactiveSwiftRex\/documentation\/ReactiveSwiftRex","doc:\/\/ReactiveSwiftRex\/documentation\/ReactiveSwiftRex\/FireAndForget"]]},"references":{"doc://ReactiveSwiftRex/documentation/ReactiveSwiftRex/FireAndForget":{"role":"symbol","title":"FireAndForget","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireAndForget"}],"abstract":[{"type":"text","text":"Fire And Forget is a SignalProducer for when you don’t care about the output of certain async operation. It’s important to notice that this"},{"type":"text","text":" "},{"type":"text","text":"operation can’t fail. If you want to also ignore the failure, then you can catchErrors and return nil in the proper init."},{"type":"text","text":" "},{"type":"text","text":"It may complete successfully when task is done."}],"identifier":"doc:\/\/ReactiveSwiftRex\/documentation\/ReactiveSwiftRex\/FireAndForget","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FireAndForget"}],"url":"\/documentation\/reactiveswiftrex\/fireandforget"},"doc://ReactiveSwiftRex/documentation/ReactiveSwiftRex/FireAndForget/Error":{"role":"symbol","title":"FireAndForget.Error","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[{"type":"text","text":"The type of error that can occur on "},{"type":"codeVoice","code":"self"},{"type":"text","text":"."}],"identifier":"doc:\/\/ReactiveSwiftRex\/documentation\/ReactiveSwiftRex\/FireAndForget\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/reactiveswiftrex\/fireandforget\/error"},"doc://ReactiveSwiftRex/documentation/ReactiveSwiftRex":{"role":"collection","title":"ReactiveSwiftRex","abstract":[],"identifier":"doc:\/\/ReactiveSwiftRex\/documentation\/ReactiveSwiftRex","kind":"symbol","type":"topic","url":"\/documentation\/reactiveswiftrex"}}}